#include <metalyzer/generator/Generator.hpp>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <vector>

namespace metalyzer {
namespace generator {

static void replaceAll(std::string &str, const std::string &from,
                       const std::string &to) {
  if (from.empty())
    return;
  size_t start_pos = 0;
  while ((start_pos = str.find(from, start_pos)) != std::string::npos) {
    str.replace(start_pos, from.length(), to);
    start_pos += to.length();
  }
}

Generator::Generator(const Config &config) : config(config) {}

std::string
Generator::serializeTable(const metalyzer::lexer::TransTable &table) const {
  std::stringstream ss;
  ss << "{\n";
  for (size_t i = 0; i < table.table.size(); ++i) {
    ss << "    {";
    for (int ch = 0; ch < 128; ++ch) {
      ss << table.table[i][ch];
      if (ch < 127)
        ss << ", ";
    }
    ss << "}";
    if (i < table.table.size() - 1)
      ss << ",";
    ss << "\n";
  }
  ss << "}";
  return ss.str();
}

std::string Generator::serializeAcceptance(
    const metalyzer::lexer::TransTable &table) const {
  std::stringstream ss;
  ss << "{";
  for (size_t i = 0; i < table.acceptRuleIds.size(); ++i) {
    ss << table.acceptRuleIds[i];
    if (i < table.acceptRuleIds.size() - 1) {
      ss << ", ";
    }
  }
  ss << "}";
  return ss.str();
}

void Generator::writeToFile(const std::string &filename,
                            const std::string &content) const {
  std::filesystem::path fullPath = config.outputDir / filename;

  if (!std::filesystem::exists(config.outputDir)) {
    std::filesystem::create_directories(config.outputDir);
  }

  std::ofstream outFile(fullPath);
  if (outFile.is_open()) {
    outFile << content;
    outFile.close();
    std::cout << "Generated: " << fullPath << std::endl;
  } else {
    std::cerr << "Error: Could not write to " << fullPath << std::endl;
  }
}

void Generator::generate(const metalyzer::lexer::TransTable &table,
                         const metalyzer::frontend::LexerSpec &spec) {
  std::string rowsStr = std::to_string(table.table.size());
  std::string tableData = serializeTable(table);
  std::string acceptData = serializeAcceptance(table);
  std::string startState = std::to_string(table.startStateId);

  std::stringstream ss;

  ss << "switch(lastGoodRule) {\n";
  for (const auto &rule : spec.rules) {
    int case_idx = rule.priority;
    std::string case_code = rule.actionCode;
    ss << "            case " << case_idx << ": " << case_code << " break;\n";
  }
  ss << "         }";

  // Create a clean, stream-compatible test execution driver block natively.
  // This cleanly overrides any legacy string-based user loops in spec blocks.
  std::stringstream test_driver_ss;
  test_driver_ss << "\n// --- AUTOGENERATED COMPATIBLE STANDALONE RUNNER ---\n";
  test_driver_ss << "int " << config.className << "_compiled_main() {\n";
  test_driver_ss << "    using namespace " << config.namespaceName << ";\n";
  test_driver_ss << "    " << config.className << " lexer(std::cin, false);\n";
  test_driver_ss << "    std::string lexeme;\n";
  test_driver_ss << "    while (lexer.hasMore()) {\n";
  test_driver_ss << "        int tok = lexer.nextToken(lexeme);\n";
  test_driver_ss << "        if (tok == -1) break;\n";
  test_driver_ss << "        if (tok == -2) {\n";
  test_driver_ss
      << "            std::cout << \"Lexical Error | Lexeme: \" << lexeme\n";
  test_driver_ss
      << "                      << \" | Line: \" << lexer.getLine()\n";
  test_driver_ss << "                      << \" | Col: \" << lexer.getCol() "
                    "<< \"\\n\";\n";
  test_driver_ss << "            continue;\n";
  test_driver_ss << "        }\n";
  test_driver_ss
      << "        std::cout << tok << \" | \" << lexeme << \" | \" << "
         "lexer.getLine() << \" | \" << lexer.getCol() << \"\\n\";\n";
  test_driver_ss << "    }\n";
  test_driver_ss << "    return 0;\n";
  test_driver_ss << "}\n";

  // --- HEADER TEMPLATE ---
  std::string header = R"(
#pragma once
#include <string>
#include <iostream>
@HEADER_CODE@

namespace @NAMESPACE@ {

class @CLASS_NAME@ {
public:
    // Takes a standard stream reference to naturally support files or live interactive std::cin
    explicit @CLASS_NAME@(std::istream& input_stream, bool enableTelemetry = false);
    ~@CLASS_NAME@();
    
    // Core scanning API - Returns -1 on EOF, -2 on Error
    int nextToken(std::string& outLexeme);
    
    // Fast inline pointer and stream check
    bool hasMore() { return (m_cursor < m_end) || (!m_stream_eof); }

    const int getLine() { return currentLine; }
    const int getCol() { return tokenStartCol; }
    
    unsigned long long getProcessedTokenCount() const { return m_total_tokens_processed; }

private:
    // Background unformatted ring-buffer loader
    void refreshBufferWindow();

    std::istream& m_stream_source;   // Abstract input data pipe
    bool m_stream_eof = false;       // Hard stream termination tracking flag
    bool m_telemetry_active = false;
    unsigned long long m_total_tokens_processed = 0;

    // Continuous block memory windows (Decouples storage life from matching loops)
    static constexpr size_t CHUNK_SIZE = 16384; // 16KB High-speed caching window
    std::string m_internal_buffer;

    const char* m_start;        // Base memory address of active ring block
    const char* m_cursor;       // Active scanning coordinate cursor
    const char* m_end;          // Valid hardware data window termination bound
    const char* m_token_start;  // Structural anchor for the current matching attempt
    
    // Coordinate tracking
    int currentLine = 1, currentCol = 1;
    int tokenStartCol = 1;

    static const int TABLE_ROWS = @TABLE_ROWS@;
    static const int TRANS_TABLE[TABLE_ROWS][128];
    static const int ACCEPT_RULES[TABLE_ROWS];
    static const int START_STATE = @START_STATE@;
};

} // namespace @NAMESPACE@
)";

  // --- SOURCE TEMPLATE (Maximal Munch Chunk-Swapping Matcher) ---
  std::string source = R"(
#include "@CLASS_NAME@.hpp"
#include <cctype>
#include <cstring>

namespace @NAMESPACE@ {

// --- STATIC TRANSITION DATA ---
const int @CLASS_NAME@::TRANS_TABLE[@TABLE_ROWS@][128] = @TABLE_DATA@;

const int @CLASS_NAME@::ACCEPT_RULES[@TABLE_ROWS@] = @ACCEPT_DATA@;

// --- ZERO-COPY ENGINE IMPLEMENTATION ---
@CLASS_NAME@::@CLASS_NAME@(std::istream& input_stream, bool enableTelemetry) 
    : m_stream_source(input_stream), 
      m_telemetry_active(enableTelemetry) {
    
    // Allocate fixed buffer room to fully avoid runtime heap-allocation resizing
    m_internal_buffer.resize(CHUNK_SIZE, '\0');
    
    m_start = m_internal_buffer.data();
    m_cursor = m_start;
    m_end = m_start;
    m_token_start = m_start;
}

@CLASS_NAME@::~@CLASS_NAME@() {
    if (m_telemetry_active) {
        std::cout << "\n[Metalyzer Runtime Telemetry]\n";
        std::cout << "  METAMETRIC_TOKEN_COUNT: " << m_total_tokens_processed << "\n";
    }
}

void @CLASS_NAME@::refreshBufferWindow() {
    if (m_stream_eof) return;

    // 1. Calculate how many unparsed bytes are sitting at the tail of the buffer
    size_t leftover_bytes = m_end - m_token_start;
    
    // 2. Shift split token fragments back to the absolute front of the storage string
    if (leftover_bytes > 0 && m_token_start > m_start) {
        std::memmove(&m_internal_buffer[0], m_token_start, leftover_bytes);
    }

    // 3. Re-align raw matching pointer offsets relative to the fresh copy displacement
    m_cursor = m_start + (m_cursor - m_token_start);
    m_token_start = m_start;

    // 4. Determine exactly how much free storage space we have left to saturate
    size_t fetch_space = CHUNK_SIZE - leftover_bytes;
    if (fetch_space == 0) {
        // Token size exceeds 16KB window limits. Handle boundary overflow.
        return;
    }

    // 5. Fire an unformatted stream read. Blocks cleanly on std::cin until interactive input is fed.
    m_stream_source.read(&m_internal_buffer[leftover_bytes], fetch_space);
    size_t bytes_fetched = m_stream_source.gcount();

    if (bytes_fetched == 0) {
        m_stream_eof = true;
        m_end = m_start + leftover_bytes;
    } else {
        m_end = m_start + leftover_bytes + bytes_fetched;
    }
}

int @CLASS_NAME@::nextToken(std::string& outLexeme) {
    // 1. Core Pointer-Driven Whitespace Skipper with Window Bounds Checks
    while (true) {
        if (m_cursor >= m_end) {
            if (m_stream_eof) break;
            refreshBufferWindow();
            if (m_cursor >= m_end) break;
        }

        char ch = *m_cursor;
        if (!std::isspace(static_cast<unsigned char>(ch))) break;

        if (ch == '\n') { 
            currentCol = 1; 
            currentLine++; 
        } else if (ch == '\t') { 
            currentCol += (4 - ((currentCol - 1) % 4)); 
        } else { 
            currentCol++; 
        }
        m_cursor++;
    }

    if (m_cursor >= m_end && m_stream_eof) return -1; // True global EOF reached
    
    m_token_start = m_cursor;
    int tokCol = currentCol;
    int currentState = START_STATE;
    
    const char* last_good_ptr = nullptr;
    int lastGoodRule = -1;

    // 2. Hot-Path Driver Loop (Zero-Allocation Memory Scan with Dynamic Buffer Refreshing)
    while (true) {
        if (m_cursor >= m_end) {
            if (m_stream_eof) break;
            refreshBufferWindow();
            if (m_cursor >= m_end) break; // End of currently loaded buffer chunk
        }

        char c = *m_cursor;
        if (c < 0 || c > 127) break; 

        int nextState = TRANS_TABLE[currentState][static_cast<int>(c)];
        if (nextState == -1) break; // Dead state reached. Halting loop.

        m_cursor++; 
        currentState = nextState;
        
        if (ACCEPT_RULES[currentState] != -1) {
            lastGoodRule = ACCEPT_RULES[currentState];
            last_good_ptr = m_cursor; // Snap current match boundary pointer
        }
    }

    // 3. Finalization Window Selection
    if (lastGoodRule != -1) {
        // Instant Maximal Munch Rollback via bare pointer assignment
        m_cursor = last_good_ptr;
        
        size_t match_length = m_cursor - m_token_start;
        
        // Extract outLexeme with a single zero-copy string assignment
        outLexeme.assign(m_token_start, match_length);

        tokenStartCol = tokCol;
        currentCol += match_length;
        
        if (m_telemetry_active) {
            m_total_tokens_processed++;
        }
        
        @ACTION_SWITCH@

        return lastGoodRule;
    } else {
        // Fallback Error Segment Isolation Block
        if (m_cursor >= m_end && !m_stream_eof) {
            refreshBufferWindow();
        }

        if (m_cursor == m_token_start) {
            char fault_char = *m_cursor;
            outLexeme.assign(m_cursor, 1);
            m_cursor++;
            
            tokenStartCol = tokCol;
            if (fault_char == '\n') { 
                currentCol = 1; 
                currentLine++; 
            } else if (fault_char == '\t') { 
                currentCol += (4 - ((currentCol - 1) % 4)); 
            } else { 
                currentCol++; 
            }
            return -2;
        } else {
            m_cursor = m_token_start;
            char fault_char = *m_cursor;
            outLexeme.assign(m_cursor, 1);
            m_cursor++; 
            
            tokenStartCol = tokCol;
            if (fault_char == '\n') { 
                currentCol = 1; 
                currentLine++; 
            } else if (fault_char == '\t') { 
                currentCol += (4 - ((currentCol - 1) % 4)); 
            } else { 
                currentCol++; 
            }
            return -2; 
        }
    }
}

} // namespace @NAMESPACE@

@USER_CODE@
@COMPATIBLE_DRIVER@
)";

  auto processTemplate = [&](std::string text) -> std::string {
    replaceAll(text, "@NAMESPACE@", config.namespaceName);
    replaceAll(text, "@CLASS_NAME@", config.className);
    replaceAll(text, "@TABLE_ROWS@", rowsStr);
    replaceAll(text, "@TABLE_DATA@", tableData);
    replaceAll(text, "@ACCEPT_DATA@", acceptData);
    replaceAll(text, "@START_STATE@", startState);
    replaceAll(text, "@ACTION_SWITCH@", ss.str());
    replaceAll(text, "@HEADER_CODE@", spec.headerCode);
    replaceAll(text, "@USER_CODE@", spec.userCode);
    replaceAll(text, "@COMPATIBLE_DRIVER@", test_driver_ss.str());
    return text;
  };

  std::string headerContent = processTemplate(header);
  std::string sourceContent = processTemplate(source);

  writeToFile(config.className + ".hpp", headerContent);
  writeToFile(config.className + ".cpp", sourceContent);
}

} // namespace generator
} // namespace metalyzer
